/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const PerformanceStats = IDL.Record({
  'totalTrades' : IDL.Nat,
  'avgRR' : IDL.Float64,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'totalPnl' : IDL.Float64,
  'openTrades' : IDL.Nat,
  'winRate' : IDL.Float64,
  'maxDrawdown' : IDL.Float64,
  'profitFactor' : IDL.Float64,
});
export const BacktestSettings = IDL.Record({
  'tp1MultiplierR' : IDL.Float64,
  'minCandlesForMA' : IDL.Nat,
  'stopBufferPct' : IDL.Float64,
  'accountSize' : IDL.Float64,
  'confluenceThreshold' : IDL.Nat,
});
export const BacktestSession = IDL.Record({
  'id' : IDL.Nat,
  'sessionLabel' : IDL.Text,
  'tradeCount' : IDL.Nat,
  'createdAt' : Timestamp,
  'stats' : PerformanceStats,
  'settings' : BacktestSettings,
});
export const Price = IDL.Float64;
export const Timeframe = IDL.Variant({
  'H1' : IDL.Null,
  'H4' : IDL.Null,
  'Daily' : IDL.Null,
});
export const Candle = IDL.Record({
  'low' : Price,
  'timeframe' : Timeframe,
  'high' : Price,
  'close' : Price,
  'open' : Price,
  'volume' : IDL.Float64,
  'timestamp' : Timestamp,
});
export const FVGZone = IDL.Record({
  'id' : IDL.Nat,
  'top' : Price,
  'isBullish' : IDL.Bool,
  'bottom' : Price,
  'timestamp' : Timestamp,
});
export const SundayLevel = IDL.Record({
  'id' : IDL.Nat,
  'levelLabel' : IDL.Text,
  'price' : Price,
  'weekTimestamp' : Timestamp,
});
export const TradeDirection = IDL.Variant({ 'Long' : IDL.Null });
export const ConfluenceScore = IDL.Record({
  'total' : IDL.Nat,
  'maHolds' : IDL.Bool,
  'hasEma20OrSma50' : IDL.Bool,
  'hasEma200' : IDL.Bool,
  'targetAbove' : IDL.Bool,
  'hasFVG' : IDL.Bool,
  'hasSundayLevel' : IDL.Bool,
  'bullishDailyCandle' : IDL.Bool,
});
export const TradeOutcome = IDL.Variant({
  'Win' : IDL.Null,
  'Loss' : IDL.Null,
  'Open' : IDL.Null,
});
export const TradeResult = IDL.Record({
  'pnl' : IDL.Opt(IDL.Float64),
  'tp1Price' : Price,
  'direction' : TradeDirection,
  'entryTimestamp' : Timestamp,
  'rMultiple' : IDL.Opt(IDL.Float64),
  'tradeId' : IDL.Nat,
  'exitTimestamp' : IDL.Opt(Timestamp),
  'entryPrice' : Price,
  'confluenceScore' : ConfluenceScore,
  'exitPrice' : IDL.Opt(Price),
  'stopPrice' : Price,
  'outcome' : TradeOutcome,
  'lotSize' : IDL.Float64,
});
export const AccountSettings = IDL.Record({
  'baseLotSize' : IDL.Float64,
  'scaleReference' : IDL.Float64,
  'accountSize' : IDL.Float64,
});
export const MovingAverages = IDL.Record({
  'ema200' : IDL.Opt(Price),
  'ema20' : IDL.Opt(Price),
  'sma50' : IDL.Opt(Price),
});

export const idlService = IDL.Service({
  '__accountSettings' : IDL.Func([], [IDL.Reserved], ['query']),
  '__backtestSessions' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(BacktestSession)],
      ['query'],
    ),
  '__candlesDaily' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Candle)],
      ['query'],
    ),
  '__candlesH1' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Candle)],
      ['query'],
    ),
  '__candlesH4' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Candle)],
      ['query'],
    ),
  '__fvgZones' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(FVGZone)],
      ['query'],
    ),
  '__state' : IDL.Func([], [IDL.Reserved], ['query']),
  '__sundayLevels' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(SundayLevel)],
      ['query'],
    ),
  '__tradeResults' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(TradeResult)))],
      ['query'],
    ),
  'addCandles' : IDL.Func([IDL.Vec(Candle)], [], []),
  'addFVGZone' : IDL.Func([Timestamp, Price, Price, IDL.Bool], [IDL.Nat], []),
  'addSundayLevel' : IDL.Func([Timestamp, Price, IDL.Text], [IDL.Nat], []),
  'deleteAllCandles' : IDL.Func([Timeframe], [], []),
  'deleteBacktestSession' : IDL.Func([IDL.Nat], [], []),
  'deleteFVGZone' : IDL.Func([IDL.Nat], [], []),
  'deleteSundayLevel' : IDL.Func([IDL.Nat], [], []),
  'getAccountSettings' : IDL.Func([], [AccountSettings], ['query']),
  'getBacktestSession' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(BacktestSession)],
      ['query'],
    ),
  'getBacktestTrades' : IDL.Func([IDL.Nat], [IDL.Vec(TradeResult)], ['query']),
  'getCandles' : IDL.Func(
      [Timeframe, IDL.Opt(Timestamp), IDL.Opt(Timestamp)],
      [IDL.Vec(Candle)],
      ['query'],
    ),
  'getFVGZones' : IDL.Func([], [IDL.Vec(FVGZone)], ['query']),
  'getMovingAverages' : IDL.Func([Timeframe], [MovingAverages], ['query']),
  'getPerformanceStats' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(PerformanceStats)],
      ['query'],
    ),
  'getSundayLevels' : IDL.Func([], [IDL.Vec(SundayLevel)], ['query']),
  'listBacktestSessions' : IDL.Func([], [IDL.Vec(BacktestSession)], ['query']),
  'runBacktest' : IDL.Func([BacktestSettings, IDL.Text], [BacktestSession], []),
  'setAccountSettings' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const PerformanceStats = IDL.Record({
    'totalTrades' : IDL.Nat,
    'avgRR' : IDL.Float64,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'totalPnl' : IDL.Float64,
    'openTrades' : IDL.Nat,
    'winRate' : IDL.Float64,
    'maxDrawdown' : IDL.Float64,
    'profitFactor' : IDL.Float64,
  });
  const BacktestSettings = IDL.Record({
    'tp1MultiplierR' : IDL.Float64,
    'minCandlesForMA' : IDL.Nat,
    'stopBufferPct' : IDL.Float64,
    'accountSize' : IDL.Float64,
    'confluenceThreshold' : IDL.Nat,
  });
  const BacktestSession = IDL.Record({
    'id' : IDL.Nat,
    'sessionLabel' : IDL.Text,
    'tradeCount' : IDL.Nat,
    'createdAt' : Timestamp,
    'stats' : PerformanceStats,
    'settings' : BacktestSettings,
  });
  const Price = IDL.Float64;
  const Timeframe = IDL.Variant({
    'H1' : IDL.Null,
    'H4' : IDL.Null,
    'Daily' : IDL.Null,
  });
  const Candle = IDL.Record({
    'low' : Price,
    'timeframe' : Timeframe,
    'high' : Price,
    'close' : Price,
    'open' : Price,
    'volume' : IDL.Float64,
    'timestamp' : Timestamp,
  });
  const FVGZone = IDL.Record({
    'id' : IDL.Nat,
    'top' : Price,
    'isBullish' : IDL.Bool,
    'bottom' : Price,
    'timestamp' : Timestamp,
  });
  const SundayLevel = IDL.Record({
    'id' : IDL.Nat,
    'levelLabel' : IDL.Text,
    'price' : Price,
    'weekTimestamp' : Timestamp,
  });
  const TradeDirection = IDL.Variant({ 'Long' : IDL.Null });
  const ConfluenceScore = IDL.Record({
    'total' : IDL.Nat,
    'maHolds' : IDL.Bool,
    'hasEma20OrSma50' : IDL.Bool,
    'hasEma200' : IDL.Bool,
    'targetAbove' : IDL.Bool,
    'hasFVG' : IDL.Bool,
    'hasSundayLevel' : IDL.Bool,
    'bullishDailyCandle' : IDL.Bool,
  });
  const TradeOutcome = IDL.Variant({
    'Win' : IDL.Null,
    'Loss' : IDL.Null,
    'Open' : IDL.Null,
  });
  const TradeResult = IDL.Record({
    'pnl' : IDL.Opt(IDL.Float64),
    'tp1Price' : Price,
    'direction' : TradeDirection,
    'entryTimestamp' : Timestamp,
    'rMultiple' : IDL.Opt(IDL.Float64),
    'tradeId' : IDL.Nat,
    'exitTimestamp' : IDL.Opt(Timestamp),
    'entryPrice' : Price,
    'confluenceScore' : ConfluenceScore,
    'exitPrice' : IDL.Opt(Price),
    'stopPrice' : Price,
    'outcome' : TradeOutcome,
    'lotSize' : IDL.Float64,
  });
  const AccountSettings = IDL.Record({
    'baseLotSize' : IDL.Float64,
    'scaleReference' : IDL.Float64,
    'accountSize' : IDL.Float64,
  });
  const MovingAverages = IDL.Record({
    'ema200' : IDL.Opt(Price),
    'ema20' : IDL.Opt(Price),
    'sma50' : IDL.Opt(Price),
  });
  
  return IDL.Service({
    '__accountSettings' : IDL.Func([], [IDL.Reserved], ['query']),
    '__backtestSessions' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(BacktestSession)],
        ['query'],
      ),
    '__candlesDaily' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Candle)],
        ['query'],
      ),
    '__candlesH1' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Candle)],
        ['query'],
      ),
    '__candlesH4' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Candle)],
        ['query'],
      ),
    '__fvgZones' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(FVGZone)],
        ['query'],
      ),
    '__state' : IDL.Func([], [IDL.Reserved], ['query']),
    '__sundayLevels' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(SundayLevel)],
        ['query'],
      ),
    '__tradeResults' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(TradeResult)))],
        ['query'],
      ),
    'addCandles' : IDL.Func([IDL.Vec(Candle)], [], []),
    'addFVGZone' : IDL.Func([Timestamp, Price, Price, IDL.Bool], [IDL.Nat], []),
    'addSundayLevel' : IDL.Func([Timestamp, Price, IDL.Text], [IDL.Nat], []),
    'deleteAllCandles' : IDL.Func([Timeframe], [], []),
    'deleteBacktestSession' : IDL.Func([IDL.Nat], [], []),
    'deleteFVGZone' : IDL.Func([IDL.Nat], [], []),
    'deleteSundayLevel' : IDL.Func([IDL.Nat], [], []),
    'getAccountSettings' : IDL.Func([], [AccountSettings], ['query']),
    'getBacktestSession' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(BacktestSession)],
        ['query'],
      ),
    'getBacktestTrades' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TradeResult)],
        ['query'],
      ),
    'getCandles' : IDL.Func(
        [Timeframe, IDL.Opt(Timestamp), IDL.Opt(Timestamp)],
        [IDL.Vec(Candle)],
        ['query'],
      ),
    'getFVGZones' : IDL.Func([], [IDL.Vec(FVGZone)], ['query']),
    'getMovingAverages' : IDL.Func([Timeframe], [MovingAverages], ['query']),
    'getPerformanceStats' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PerformanceStats)],
        ['query'],
      ),
    'getSundayLevels' : IDL.Func([], [IDL.Vec(SundayLevel)], ['query']),
    'listBacktestSessions' : IDL.Func(
        [],
        [IDL.Vec(BacktestSession)],
        ['query'],
      ),
    'runBacktest' : IDL.Func(
        [BacktestSettings, IDL.Text],
        [BacktestSession],
        [],
      ),
    'setAccountSettings' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };