/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccountSettings {
  'baseLotSize' : number,
  'scaleReference' : number,
  'accountSize' : number,
}
export interface BacktestSession {
  'id' : bigint,
  'sessionLabel' : string,
  'tradeCount' : bigint,
  'createdAt' : Timestamp,
  'stats' : PerformanceStats,
  'settings' : BacktestSettings,
}
export interface BacktestSettings {
  'tp1MultiplierR' : number,
  'minCandlesForMA' : bigint,
  'stopBufferPct' : number,
  'accountSize' : number,
  'confluenceThreshold' : bigint,
}
export interface Candle {
  'low' : Price,
  'timeframe' : Timeframe,
  'high' : Price,
  'close' : Price,
  'open' : Price,
  'volume' : number,
  'timestamp' : Timestamp,
}
export interface ConfluenceScore {
  'total' : bigint,
  'maHolds' : boolean,
  'hasEma20OrSma50' : boolean,
  'hasEma200' : boolean,
  'targetAbove' : boolean,
  'hasFVG' : boolean,
  'hasSundayLevel' : boolean,
  'bullishDailyCandle' : boolean,
}
export interface FVGZone {
  'id' : bigint,
  'top' : Price,
  'isBullish' : boolean,
  'bottom' : Price,
  'timestamp' : Timestamp,
}
export interface MovingAverages {
  'ema200' : [] | [Price],
  'ema20' : [] | [Price],
  'sma50' : [] | [Price],
}
export interface PerformanceStats {
  'totalTrades' : bigint,
  'avgRR' : number,
  'wins' : bigint,
  'losses' : bigint,
  'totalPnl' : number,
  'openTrades' : bigint,
  'winRate' : number,
  'maxDrawdown' : number,
  'profitFactor' : number,
}
export type Price = number;
export interface SundayLevel {
  'id' : bigint,
  'levelLabel' : string,
  'price' : Price,
  'weekTimestamp' : Timestamp,
}
export type Timeframe = { 'H1' : null } |
  { 'H4' : null } |
  { 'Daily' : null };
export type Timestamp = bigint;
export type TradeDirection = { 'Long' : null };
export type TradeOutcome = { 'Win' : null } |
  { 'Loss' : null } |
  { 'Open' : null };
export interface TradeResult {
  'pnl' : [] | [number],
  'tp1Price' : Price,
  'direction' : TradeDirection,
  'entryTimestamp' : Timestamp,
  'rMultiple' : [] | [number],
  'tradeId' : bigint,
  'exitTimestamp' : [] | [Timestamp],
  'entryPrice' : Price,
  'confluenceScore' : ConfluenceScore,
  'exitPrice' : [] | [Price],
  'stopPrice' : Price,
  'outcome' : TradeOutcome,
  'lotSize' : number,
}
export interface _SERVICE {
  '__accountSettings' : ActorMethod<[], any>,
  '__backtestSessions' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<BacktestSession>
  >,
  '__candlesDaily' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Candle>>,
  '__candlesH1' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Candle>>,
  '__candlesH4' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Candle>>,
  '__fvgZones' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<FVGZone>>,
  '__state' : ActorMethod<[], any>,
  '__sundayLevels' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<SundayLevel>
  >,
  '__tradeResults' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<[bigint, Array<TradeResult>]>
  >,
  'addCandles' : ActorMethod<[Array<Candle>], undefined>,
  'addFVGZone' : ActorMethod<[Timestamp, Price, Price, boolean], bigint>,
  'addSundayLevel' : ActorMethod<[Timestamp, Price, string], bigint>,
  'deleteAllCandles' : ActorMethod<[Timeframe], undefined>,
  'deleteBacktestSession' : ActorMethod<[bigint], undefined>,
  'deleteFVGZone' : ActorMethod<[bigint], undefined>,
  'deleteSundayLevel' : ActorMethod<[bigint], undefined>,
  'getAccountSettings' : ActorMethod<[], AccountSettings>,
  'getBacktestSession' : ActorMethod<[bigint], [] | [BacktestSession]>,
  'getBacktestTrades' : ActorMethod<[bigint], Array<TradeResult>>,
  'getCandles' : ActorMethod<
    [Timeframe, [] | [Timestamp], [] | [Timestamp]],
    Array<Candle>
  >,
  'getFVGZones' : ActorMethod<[], Array<FVGZone>>,
  'getMovingAverages' : ActorMethod<[Timeframe], MovingAverages>,
  'getPerformanceStats' : ActorMethod<[bigint], [] | [PerformanceStats]>,
  'getSundayLevels' : ActorMethod<[], Array<SundayLevel>>,
  'listBacktestSessions' : ActorMethod<[], Array<BacktestSession>>,
  'runBacktest' : ActorMethod<[BacktestSettings, string], BacktestSession>,
  'setAccountSettings' : ActorMethod<[number, number, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];