/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface AccountSettings {
    baseLotSize: number;
    scaleReference: number;
    accountSize: number;
}
export interface TradeResult {
    pnl?: number;
    tp1Price: Price;
    direction: TradeDirection;
    entryTimestamp: Timestamp;
    rMultiple?: number;
    tradeId: bigint;
    exitTimestamp?: Timestamp;
    entryPrice: Price;
    confluenceScore: ConfluenceScore;
    exitPrice?: Price;
    stopPrice: Price;
    outcome: TradeOutcome;
    lotSize: number;
}
export type Price = number;
export interface PerformanceStats {
    totalTrades: bigint;
    avgRR: number;
    wins: bigint;
    losses: bigint;
    totalPnl: number;
    openTrades: bigint;
    winRate: number;
    maxDrawdown: number;
    profitFactor: number;
}
export interface SundayLevel {
    id: bigint;
    levelLabel: string;
    price: Price;
    weekTimestamp: Timestamp;
}
export interface MovingAverages {
    ema200?: Price;
    ema20?: Price;
    sma50?: Price;
}
export interface ConfluenceScore {
    total: bigint;
    maHolds: boolean;
    hasEma20OrSma50: boolean;
    hasEma200: boolean;
    targetAbove: boolean;
    hasFVG: boolean;
    hasSundayLevel: boolean;
    bullishDailyCandle: boolean;
}
export interface Candle {
    low: Price;
    timeframe: Timeframe;
    high: Price;
    close: Price;
    open: Price;
    volume: number;
    timestamp: Timestamp;
}
export interface BacktestSettings {
    tp1MultiplierR: number;
    minCandlesForMA: bigint;
    stopBufferPct: number;
    accountSize: number;
    confluenceThreshold: bigint;
}
export interface BacktestSession {
    id: bigint;
    sessionLabel: string;
    tradeCount: bigint;
    createdAt: Timestamp;
    stats: PerformanceStats;
    settings: BacktestSettings;
}
export interface FVGZone {
    id: bigint;
    top: Price;
    isBullish: boolean;
    bottom: Price;
    timestamp: Timestamp;
}
export enum Timeframe {
    H1 = "H1",
    H4 = "H4",
    Daily = "Daily"
}
export enum TradeDirection {
    Long = "Long"
}
export enum TradeOutcome {
    Win = "Win",
    Loss = "Loss",
    Open = "Open"
}
export interface backendInterface {
    __accountSettings(): Promise<any>;
    __backtestSessions(io: bigint | null, count: bigint | null): Promise<Array<BacktestSession>>;
    __candlesDaily(io: bigint | null, count: bigint | null): Promise<Array<Candle>>;
    __candlesH1(io: bigint | null, count: bigint | null): Promise<Array<Candle>>;
    __candlesH4(io: bigint | null, count: bigint | null): Promise<Array<Candle>>;
    __fvgZones(io: bigint | null, count: bigint | null): Promise<Array<FVGZone>>;
    __state(): Promise<any>;
    __sundayLevels(io: bigint | null, count: bigint | null): Promise<Array<SundayLevel>>;
    __tradeResults(ko: bigint | null, count: bigint | null): Promise<Array<[bigint, Array<TradeResult>]>>;
    addCandles(newCandles: Array<Candle>): Promise<void>;
    addFVGZone(timestamp: Timestamp, top: Price, bottom: Price, isBullish: boolean): Promise<bigint>;
    addSundayLevel(weekTimestamp: Timestamp, price: Price, levelLabel: string): Promise<bigint>;
    deleteAllCandles(timeframe: Timeframe): Promise<void>;
    deleteBacktestSession(id: bigint): Promise<void>;
    deleteFVGZone(id: bigint): Promise<void>;
    deleteSundayLevel(id: bigint): Promise<void>;
    getAccountSettings(): Promise<AccountSettings>;
    getBacktestSession(id: bigint): Promise<BacktestSession | null>;
    getBacktestTrades(sessionId: bigint): Promise<Array<TradeResult>>;
    getCandles(timeframe: Timeframe, from: Timestamp | null, to: Timestamp | null): Promise<Array<Candle>>;
    getFVGZones(): Promise<Array<FVGZone>>;
    getMovingAverages(timeframe: Timeframe): Promise<MovingAverages>;
    getPerformanceStats(sessionId: bigint): Promise<PerformanceStats | null>;
    getSundayLevels(): Promise<Array<SundayLevel>>;
    listBacktestSessions(): Promise<Array<BacktestSession>>;
    runBacktest(settings: BacktestSettings, sessionLabel: string): Promise<BacktestSession>;
    setAccountSettings(accountSize: number, baseLotSize: number, scaleReference: number): Promise<void>;
}
import type { BacktestSession as _BacktestSession, Candle as _Candle, ConfluenceScore as _ConfluenceScore, MovingAverages as _MovingAverages, PerformanceStats as _PerformanceStats, Price as _Price, Timeframe as _Timeframe, Timestamp as _Timestamp, TradeDirection as _TradeDirection, TradeOutcome as _TradeOutcome, TradeResult as _TradeResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __accountSettings(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__accountSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__accountSettings();
            return result;
        }
    }
    async __backtestSessions(arg0: bigint | null, arg1: bigint | null): Promise<Array<BacktestSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.__backtestSessions(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__backtestSessions(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __candlesDaily(arg0: bigint | null, arg1: bigint | null): Promise<Array<Candle>> {
        if (this.processError) {
            try {
                const result = await this.actor.__candlesDaily(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__candlesDaily(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async __candlesH1(arg0: bigint | null, arg1: bigint | null): Promise<Array<Candle>> {
        if (this.processError) {
            try {
                const result = await this.actor.__candlesH1(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__candlesH1(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async __candlesH4(arg0: bigint | null, arg1: bigint | null): Promise<Array<Candle>> {
        if (this.processError) {
            try {
                const result = await this.actor.__candlesH4(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__candlesH4(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async __fvgZones(arg0: bigint | null, arg1: bigint | null): Promise<Array<FVGZone>> {
        if (this.processError) {
            try {
                const result = await this.actor.__fvgZones(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__fvgZones(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __state(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__state();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__state();
            return result;
        }
    }
    async __sundayLevels(arg0: bigint | null, arg1: bigint | null): Promise<Array<SundayLevel>> {
        if (this.processError) {
            try {
                const result = await this.actor.__sundayLevels(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__sundayLevels(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __tradeResults(arg0: bigint | null, arg1: bigint | null): Promise<Array<[bigint, Array<TradeResult>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__tradeResults(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__tradeResults(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async addCandles(arg0: Array<Candle>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCandles(to_candid_vec_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCandles(to_candid_vec_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addFVGZone(arg0: Timestamp, arg1: Price, arg2: Price, arg3: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addFVGZone(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFVGZone(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addSundayLevel(arg0: Timestamp, arg1: Price, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSundayLevel(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSundayLevel(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteAllCandles(arg0: Timeframe): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllCandles(to_candid_Timeframe_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllCandles(to_candid_Timeframe_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteBacktestSession(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBacktestSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBacktestSession(arg0);
            return result;
        }
    }
    async deleteFVGZone(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFVGZone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFVGZone(arg0);
            return result;
        }
    }
    async deleteSundayLevel(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSundayLevel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSundayLevel(arg0);
            return result;
        }
    }
    async getAccountSettings(): Promise<AccountSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccountSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccountSettings();
            return result;
        }
    }
    async getBacktestSession(arg0: bigint): Promise<BacktestSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBacktestSession(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBacktestSession(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBacktestTrades(arg0: bigint): Promise<Array<TradeResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBacktestTrades(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBacktestTrades(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandles(arg0: Timeframe, arg1: Timestamp | null, arg2: Timestamp | null): Promise<Array<Candle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandles(to_candid_Timeframe_n22(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandles(to_candid_Timeframe_n22(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFVGZones(): Promise<Array<FVGZone>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFVGZones();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFVGZones();
            return result;
        }
    }
    async getMovingAverages(arg0: Timeframe): Promise<MovingAverages> {
        if (this.processError) {
            try {
                const result = await this.actor.getMovingAverages(to_candid_Timeframe_n22(this._uploadFile, this._downloadFile, arg0));
                return from_candid_MovingAverages_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMovingAverages(to_candid_Timeframe_n22(this._uploadFile, this._downloadFile, arg0));
            return from_candid_MovingAverages_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPerformanceStats(arg0: bigint): Promise<PerformanceStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPerformanceStats(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPerformanceStats(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSundayLevels(): Promise<Array<SundayLevel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSundayLevels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSundayLevels();
            return result;
        }
    }
    async listBacktestSessions(): Promise<Array<BacktestSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBacktestSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBacktestSessions();
            return result;
        }
    }
    async runBacktest(arg0: BacktestSettings, arg1: string): Promise<BacktestSession> {
        if (this.processError) {
            try {
                const result = await this.actor.runBacktest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runBacktest(arg0, arg1);
            return result;
        }
    }
    async setAccountSettings(arg0: number, arg1: number, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAccountSettings(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAccountSettings(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_Candle_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Candle): Candle {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_MovingAverages_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MovingAverages): MovingAverages {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Timeframe_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Timeframe): Timeframe {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_TradeDirection_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeDirection): TradeDirection {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_TradeOutcome_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeOutcome): TradeOutcome {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_TradeResult_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeResult): TradeResult {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Price]): Price | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BacktestSession]): BacktestSession | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PerformanceStats]): PerformanceStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pnl: [] | [number];
    tp1Price: _Price;
    direction: _TradeDirection;
    entryTimestamp: _Timestamp;
    rMultiple: [] | [number];
    tradeId: bigint;
    exitTimestamp: [] | [_Timestamp];
    entryPrice: _Price;
    confluenceScore: _ConfluenceScore;
    exitPrice: [] | [_Price];
    stopPrice: _Price;
    outcome: _TradeOutcome;
    lotSize: number;
}): {
    pnl?: number;
    tp1Price: Price;
    direction: TradeDirection;
    entryTimestamp: Timestamp;
    rMultiple?: number;
    tradeId: bigint;
    exitTimestamp?: Timestamp;
    entryPrice: Price;
    confluenceScore: ConfluenceScore;
    exitPrice?: Price;
    stopPrice: Price;
    outcome: TradeOutcome;
    lotSize: number;
} {
    return {
        pnl: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.pnl)),
        tp1Price: value.tp1Price,
        direction: from_candid_TradeDirection_n13(_uploadFile, _downloadFile, value.direction),
        entryTimestamp: value.entryTimestamp,
        rMultiple: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.rMultiple)),
        tradeId: value.tradeId,
        exitTimestamp: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.exitTimestamp)),
        entryPrice: value.entryPrice,
        confluenceScore: value.confluenceScore,
        exitPrice: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.exitPrice)),
        stopPrice: value.stopPrice,
        outcome: from_candid_TradeOutcome_n17(_uploadFile, _downloadFile, value.outcome),
        lotSize: value.lotSize
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ema200: [] | [_Price];
    ema20: [] | [_Price];
    sma50: [] | [_Price];
}): {
    ema200?: Price;
    ema20?: Price;
    sma50?: Price;
} {
    return {
        ema200: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.ema200)),
        ema20: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.ema20)),
        sma50: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.sma50))
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: _Price;
    timeframe: _Timeframe;
    high: _Price;
    close: _Price;
    open: _Price;
    volume: number;
    timestamp: _Timestamp;
}): {
    low: Price;
    timeframe: Timeframe;
    high: Price;
    close: Price;
    open: Price;
    volume: number;
    timestamp: Timestamp;
} {
    return {
        low: value.low,
        timeframe: from_candid_Timeframe_n5(_uploadFile, _downloadFile, value.timeframe),
        high: value.high,
        close: value.close,
        open: value.open,
        volume: value.volume,
        timestamp: value.timestamp
    };
}
function from_candid_tuple_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, Array<_TradeResult>]): [bigint, Array<TradeResult>] {
    return [
        value[0],
        from_candid_vec_n9(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Long: null;
}): TradeDirection {
    return "Long" in value ? TradeDirection.Long : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Win: null;
} | {
    Loss: null;
} | {
    Open: null;
}): TradeOutcome {
    return "Win" in value ? TradeOutcome.Win : "Loss" in value ? TradeOutcome.Loss : "Open" in value ? TradeOutcome.Open : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    H1: null;
} | {
    H4: null;
} | {
    Daily: null;
}): Timeframe {
    return "H1" in value ? Timeframe.H1 : "H4" in value ? Timeframe.H4 : "Daily" in value ? Timeframe.Daily : value;
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Candle>): Array<Candle> {
    return value.map((x)=>from_candid_Candle_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, Array<_TradeResult>]>): Array<[bigint, Array<TradeResult>]> {
    return value.map((x)=>from_candid_tuple_n8(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TradeResult>): Array<TradeResult> {
    return value.map((x)=>from_candid_TradeResult_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Candle_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Candle): _Candle {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_Timeframe_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timeframe): _Timeframe {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: Price;
    timeframe: Timeframe;
    high: Price;
    close: Price;
    open: Price;
    volume: number;
    timestamp: Timestamp;
}): {
    low: _Price;
    timeframe: _Timeframe;
    high: _Price;
    close: _Price;
    open: _Price;
    volume: number;
    timestamp: _Timestamp;
} {
    return {
        low: value.low,
        timeframe: to_candid_Timeframe_n22(_uploadFile, _downloadFile, value.timeframe),
        high: value.high,
        close: value.close,
        open: value.open,
        volume: value.volume,
        timestamp: value.timestamp
    };
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timeframe): {
    H1: null;
} | {
    H4: null;
} | {
    Daily: null;
} {
    return value == Timeframe.H1 ? {
        H1: null
    } : value == Timeframe.H4 ? {
        H4: null
    } : value == Timeframe.Daily ? {
        Daily: null
    } : value;
}
function to_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Candle>): Array<_Candle> {
    return value.map((x)=>to_candid_Candle_n20(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
